apiVersion: apps/v1
kind: Deployment
metadata:
  name: aigw-processor-complexity-classifier
  labels:
    app: aigw-processor-complexity-classifier
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: aigw-processor-complexity-classifier
  template:
    metadata:
      labels:
        app: aigw-processor-complexity-classifier
    spec:
      containers:
        - name: aigw-processor-complexity-classifier
          image: sorinboiaf5/aigw-processor-complexity-classifier:latest
          ports:
            - containerPort: 9999
       
---
apiVersion: v1
kind: Service
metadata:
  name: aigw-processor-complexity-classifier
spec:
  selector:
    app: aigw-processor-complexity-classifier
  ports:
    - protocol: HTTP
      port: 9999
      targetPort: 9999
  type: ClusterIP  
